### ISSUE TITLE
Example for FLDecisionTree is wrong

### ISSUE THREAD

**Issue by rohit-gupta** [Fuzzy-Logix/AdapteR#1]
Response variable for decision tree must be categorical

**Comment by rohit-gupta** [comment]
@mitulm Have there been any developments on this issue ?

**Comment by animator** [comment]
i think @mitulm doesn't know about these issue notifications. Raise a JIRA.

**Comment by mitulm** [comment]
@animator i do get notifications and we have already talked about this thing..

**Comment by rohit-gupta** [comment]
This issue has been discussed and a solution has been found, we will make the changes as appropriate, since this is low priority, as the example is syntactically and functionally correct, only wrong in a semantic sense.

**Comment by gkappler** [comment]
regarded old version
