### ISSUE TITLE
install_github throws a strange error

### ISSUE THREAD

**Issue by animator** [Fuzzy-Logix/AdapteR#13]
```
> install_github("Fuzzy-Logix/AdapteR")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)
```

After doing some google search I got it installed using the following command:
`install_git("git://github.com/Fuzzy-Logix/AdapteR.git")`

Sources:
http://stackoverflow.com/questions/31643036/devtoolsinstall-github-fails-with-ca-cert-error
https://support.rstudio.com/hc/en-us/community/posts/207834038-Getting-error-messages-when-installing-the-new-addins-package

The readme.org file should be edited.

**Comment by gkappler** [comment]
Thanks for reporting.  This issue is surfacing for the second time now, and seems to involve a specific setup of ssh on some but not all windows installations.  
We do not want the readme too convoluted.  We will however include this in a troubleshooting site.
